server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Pages d'erreur custom
    error_page 404 /error-pages/404.html;
    error_page 500 502 504 /error-pages/500.html;
    error_page 503 /error-pages/503.html;

    location /error-pages/ {
        root /usr/share/nginx/html;
        internal;
    }

    # Page de maintenance globale
    # Décommenter pour activer la maintenance :
    # return 503;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://gateway-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
