sonar.projectKey=joseph-yusuf-frontend
sonar.projectName=Joseph Yusuf - Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/joseph-yusuf/lcov.info
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/environments/**,**/assets/**
sonar.sourceEncoding=UTF-8
sonar.host.url=${env.SONARQUBE_URL}
