sonar.projectKey=joseph-yusuf-frontend
sonar.projectName=Joseph Yusuf - Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/joseph-yusuf/lcov.info
sonar.typescript.lcov.reportPaths=coverage/joseph-yusuf/lcov.info
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/test.ts,**/smoke.spec.ts
sonar.coverage.exclusions=**/landing/**,**/environments/**,**/models/**,**/app.config.ts,**/app.routes.ts
sonar.sourceEncoding=UTF-8
sonar.host.url=${env.SONARQUBE_URL}
