ALTER TABLE joseph_auth.users
    ADD COLUMN IF NOT EXISTS trial_started_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS trial_ends_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS trial_used BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_in_trial BOOLEAN DEFAULT FALSE;
