all:
  hosts:
    joseph-prod:
      ansible_host: 178.105.151.226
      ansible_user: deploy
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
      ansible_python_interpreter: /usr/bin/python3
  vars:
    env_name: production
    domain: josephyusuf.com
