-- V5: Knowledge base V2 — Épargne limites plan, tips répartition, codes promo, support limites

-- ============================================================
-- ÉPARGNE — Limites par plan, historique versements
-- ============================================================

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'Combien d''objectifs d''épargne puis-je créer ?',
    'Le nombre d''objectifs d''épargne dépend de votre plan :

• **FREE** : 1 objectif maximum
• **PREMIUM** : jusqu''à 5 objectifs simultanés
• **PREMIUM PLUS** : objectifs illimités

Si vous atteignez la limite de votre plan, vous serez invité à passer au plan supérieur. Les objectifs terminés (COMPLETED) ou annulés (CANCELLED) ne comptent pas dans la limite.

**Astuce :** en plan FREE, concentrez-vous sur un seul objectif prioritaire (fonds d''urgence recommandé). Passez en PREMIUM pour diversifier vos objectifs.',
    'INCOME', 'épargne,objectif,limite,plan,free,premium', 'fr', 'FREE', null, 0, true, NOW(), NOW());

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'How many savings goals can I create?',
    'The number of savings goals depends on your plan:

• **FREE**: 1 goal maximum
• **PREMIUM**: up to 5 simultaneous goals
• **PREMIUM PLUS**: unlimited goals

If you reach your plan''s limit, you will be prompted to upgrade. Completed or cancelled goals do not count toward the limit.

**Tip:** on the FREE plan, focus on one priority goal (emergency fund recommended). Upgrade to PREMIUM to diversify your goals.',
    'INCOME', 'savings,goal,limit,plan,free,premium', 'en', 'FREE', null, 0, true, NOW(), NOW());

-- ---

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'Comment consulter l''historique de mes versements ?',
    'L''historique de vos versements d''épargne est accessible depuis le détail de chaque objectif.

**Profondeur de l''historique selon votre plan :**

• **FREE** : 3 derniers mois uniquement
• **PREMIUM** : 12 derniers mois
• **PREMIUM PLUS** : historique complet depuis la création de l''objectif

**Ce que vous y trouverez :**
• Date du versement
• Montant versé
• Type : AUTOMATIQUE (généré par la recommandation) ou MANUEL (ajouté par vous)
• Statut Joseph du mois associé (Abondance, Normal ou Disette)
• Note optionnelle

**Export :** l''export des versements est disponible uniquement en plan PREMIUM et PREMIUM PLUS.',
    'INCOME', 'versement,historique,épargne,contribution,export', 'fr', 'FREE', null, 0, true, NOW(), NOW());

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'How to view my contribution history?',
    'Your savings contribution history is accessible from each goal''s detail page.

**History depth by plan:**

• **FREE**: last 3 months only
• **PREMIUM**: last 12 months
• **PREMIUM PLUS**: full history since goal creation

**What you''ll find:**
• Contribution date
• Amount contributed
• Type: AUTOMATIC (generated by recommendation) or MANUAL (added by you)
• Joseph status of the associated month (Abundance, Normal or Lean)
• Optional note

**Export:** contribution export is available on PREMIUM and PREMIUM PLUS plans only.',
    'INCOME', 'contribution,history,savings,export', 'en', 'FREE', null, 0, true, NOW(), NOW());

-- ============================================================
-- REVENUS — Astuces de répartition physique
-- ============================================================

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'Comment voir les astuces de répartition physique de mon argent ?',
    'Après chaque saisie de revenu, Joseph·Yusuf vous propose des astuces concrètes pour répartir physiquement votre argent selon votre pays et votre situation.

**Accès :**
• Le bouton « Astuces répartition » apparaît après la saisie d''un revenu
• Il est aussi disponible en permanence sur le dashboard

**Contenu de la modal :**
• Votre revenu total du mois et le statut Joseph
• La répartition recommandée (50 % besoins / 30 % envies / 20 % épargne)
• Des astuces adaptées à votre pays et votre plan

**Langue :**
• Basculez entre français et anglais avec le switch FR/EN en haut de la modal
• Votre préférence de langue est mémorisée

**Par statut Joseph :**
• En ABONDANCE : les conseils d''investissement sont mis en avant
• En DISETTE : les conseils d''investissement sont masqués, priorité aux solutions d''urgence
• En NORMAL : ordre par défaut',
    'INCOME', 'astuces,répartition,tips,argent,modal,enveloppes', 'fr', 'FREE', null, 0, true, NOW(), NOW());

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'How to view money allocation tips?',
    'After each income entry, Joseph·Yusuf offers practical tips to physically allocate your money based on your country and situation.

**Access:**
• The "Allocation tips" button appears after entering an income
• It is also permanently available on the dashboard

**Modal content:**
• Your total monthly income and Joseph status
• Recommended split (50% needs / 30% wants / 20% savings)
• Tips adapted to your country and plan

**Language:**
• Switch between French and English with the FR/EN toggle at the top
• Your language preference is remembered

**By Joseph status:**
• In ABUNDANCE: investment tips are highlighted
• In LEAN: investment tips are hidden, priority to emergency solutions
• In NORMAL: default order',
    'INCOME', 'tips,allocation,money,modal,envelopes', 'en', 'FREE', null, 0, true, NOW(), NOW());

-- ---

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'Quelles astuces de répartition sont disponibles selon mon pays ?',
    'Les astuces s''adaptent à votre pays (défini dans votre profil) :

**Universelles (tous les pays) :**
• Le système des enveloppes — répartir physiquement en catégories
• La tontine avec des personnes de confiance

**Sénégal, Côte d''Ivoire, Mali, Guinée :**
• Les coffres Wave — créer des sous-comptes par objectif dans l''app Wave

**Sénégal, Côte d''Ivoire, Mali, Cameroun :**
• L''épargne Orange Money — utiliser la fonction épargne intégrée d''Orange Money

**Cameroun :**
• Le Likelemba numérique — adaptation digitale de la tontine camerounaise

**France, Belgique :**
• Un compte épargne dédié par objectif — Livret A, LDDS ou livret bancaire

**Conseils avancés (PREMIUM) :**
• La stratégie multi-comptes — segmenter son argent par objectif de vie
• L''épargne automatique — se payer en premier dès réception du revenu

**Conseils investissement (PREMIUM PLUS) :**
• Commencer à investir progressivement
• Investir à la BRVM (Sénégal, Côte d''Ivoire, Mali, Guinée, Burkina, Togo, Bénin, Niger)',
    'INCOME', 'astuces,pays,wave,orange,enveloppes,tontine,likelemba,brvm', 'fr', 'FREE', null, 0, true, NOW(), NOW());

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'What allocation tips are available for my country?',
    'Tips adapt to your country (set in your profile):

**Universal (all countries):**
• The envelope system — physically split money into categories
• Tontine with trusted people

**Senegal, Ivory Coast, Mali, Guinea:**
• Wave safes — create sub-accounts per goal in the Wave app

**Senegal, Ivory Coast, Mali, Cameroon:**
• Orange Money savings — use Orange Money''s built-in savings feature

**Cameroon:**
• Digital Likelemba — digital adaptation of the Cameroonian tontine

**France, Belgium:**
• A dedicated savings account per goal — Livret A, LDDS or bank savings account

**Advanced tips (PREMIUM):**
• Multi-account strategy — segment money by life goal
• Automatic savings — pay yourself first when income arrives

**Investment tips (PREMIUM PLUS):**
• Start investing progressively
• Invest on the BRVM (Senegal, Ivory Coast, Mali, Guinea, Burkina, Togo, Benin, Niger)',
    'INCOME', 'tips,country,wave,orange,envelopes,tontine,likelemba,brvm', 'en', 'FREE', null, 0, true, NOW(), NOW());

-- ============================================================
-- COMPTE — Profil pays/devise, code promo inscription
-- ============================================================

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'Comment mettre à jour mon pays et ma devise ?',
    'Votre pays et votre devise influencent les astuces de répartition qui vous sont proposées.

**Modifier votre profil :**
1. Accédez aux paramètres de votre compte (icône profil).
2. Modifiez les champs « Pays » et « Devise ».
3. Enregistrez.

**Impact :**
• Les astuces de répartition physique s''adaptent à votre pays (Wave pour le Sénégal, Livret A pour la France, etc.).
• La devise affichée dans les astuces correspond à votre devise de profil.

**Valeurs par défaut :** Sénégal (SN) et XOF (franc CFA).

**Pays supportés pour les astuces spécifiques :**
SN (Sénégal), CI (Côte d''Ivoire), ML (Mali), GN (Guinée), CM (Cameroun), FR (France), BE (Belgique), BF (Burkina Faso), TG (Togo), BJ (Bénin), NE (Niger).',
    'ACCOUNT', 'pays,devise,profil,country,currency,paramètres', 'fr', 'FREE', null, 0, true, NOW(), NOW());

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'How to update my country and currency?',
    'Your country and currency influence the allocation tips shown to you.

**Update your profile:**
1. Go to your account settings (profile icon).
2. Edit the "Country" and "Currency" fields.
3. Save.

**Impact:**
• Money allocation tips adapt to your country (Wave for Senegal, Livret A for France, etc.).
• The currency shown in tips matches your profile currency.

**Default values:** Senegal (SN) and XOF (CFA franc).

**Supported countries for specific tips:**
SN (Senegal), CI (Ivory Coast), ML (Mali), GN (Guinea), CM (Cameroon), FR (France), BE (Belgium), BF (Burkina Faso), TG (Togo), BJ (Benin), NE (Niger).',
    'ACCOUNT', 'country,currency,profile,settings,update', 'en', 'FREE', null, 0, true, NOW(), NOW());

-- ---

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'Comment utiliser un code promo à l''inscription ?',
    'Vous pouvez bénéficier d''une réduction sur votre premier abonnement grâce à un code promo.

**Méthode 1 — Lien direct (automatique) :**
Si quelqu''un vous partage un lien d''inscription contenant un code promo (ex: josephyusuf.com/register?promo=CODE), le code est détecté et validé automatiquement. Un bandeau vert confirme l''application.

**Méthode 2 — Saisie manuelle :**
1. Sur la page d''inscription, cliquez « Vous avez un code promo ? ».
2. Entrez votre code.
3. Inscrivez-vous normalement.

**Application de la réduction :**
• Le code est revalidé au moment du paiement (page Abonnement).
• S''il est toujours valide, la réduction s''applique automatiquement.
• Vous pouvez aussi saisir ou changer de code manuellement sur la page d''abonnement.

**Cas d''invalidité :**
• Code inexistant
• Code expiré
• Code ayant atteint son nombre maximum d''utilisations
• Un code invalide ne bloque pas l''inscription — vous pouvez vous inscrire sans.',
    'ACCOUNT', 'code promo,inscription,réduction,lien,register,promo', 'fr', 'FREE', null, 0, true, NOW(), NOW());

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'How to use a promo code at registration?',
    'You can get a discount on your first subscription with a promo code.

**Method 1 — Direct link (automatic):**
If someone shares a registration link containing a promo code (e.g., josephyusuf.com/register?promo=CODE), the code is automatically detected and validated. A green banner confirms application.

**Method 2 — Manual entry:**
1. On the registration page, click "Have a promo code?".
2. Enter your code.
3. Register normally.

**Discount application:**
• The code is revalidated at payment time (Subscription page).
• If still valid, the discount is applied automatically.
• You can also enter or change a code manually on the subscription page.

**Invalidity reasons:**
• Code does not exist
• Code has expired
• Code has reached its maximum number of uses
• An invalid code does not block registration — you can sign up without it.',
    'ACCOUNT', 'promo code,registration,discount,link,register', 'en', 'FREE', null, 0, true, NOW(), NOW());

-- ============================================================
-- ABONNEMENT — Codes promo détails
-- ============================================================

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'Comment fonctionnent les codes promo ?',
    'Les codes promo offrent une réduction en pourcentage sur votre premier mois d''abonnement.

**Caractéristiques :**
• Réduction en % sur le premier paiement (ex : -20 %)
• Usage unique par utilisateur — un code ne peut être utilisé qu''une seule fois par compte
• Vérification automatique de validité au moment du paiement

**Utilisation :**
1. Le code peut être pré-rempli via un lien d''inscription (?promo=CODE) ou saisi manuellement.
2. Sur la page Abonnement, le champ code promo affiche la réduction si le code est valide.
3. Le prix barré et le prix réduit sont affichés dans le récapitulatif.

**Raisons d''invalidité :**
• **Expiré** : le code a une date d''expiration dépassée
• **Épuisé** : le code a atteint son nombre maximum d''utilisations
• **Inexistant** : le code n''existe pas ou a été désactivé

**Important :** la réduction s''applique uniquement au premier mois. Les mois suivants sont facturés au tarif normal.',
    'SUBSCRIPTION', 'code promo,réduction,coupon,discount,premier mois', 'fr', 'FREE', null, 0, true, NOW(), NOW());

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'How do promo codes work?',
    'Promo codes offer a percentage discount on your first month of subscription.

**Features:**
• Percentage discount on the first payment (e.g., -20%)
• Single use per user — a code can only be used once per account
• Automatic validity check at payment time

**Usage:**
1. The code can be pre-filled via a registration link (?promo=CODE) or entered manually.
2. On the Subscription page, the promo code field shows the discount if valid.
3. The crossed-out price and discounted price are displayed in the summary.

**Invalidity reasons:**
• **Expired**: the code has passed its expiration date
• **Exhausted**: the code has reached its maximum number of uses
• **Not found**: the code does not exist or has been deactivated

**Important:** the discount applies only to the first month. Subsequent months are billed at the normal rate.',
    'SUBSCRIPTION', 'promo code,discount,coupon,first month', 'en', 'FREE', null, 0, true, NOW(), NOW());

-- ============================================================
-- SUPPORT — Limites tickets par plan, délais
-- ============================================================

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'Combien de tickets de support puis-je ouvrir ?',
    'Le nombre de tickets de support ouverts simultanément dépend de votre plan :

• **FREE** : 2 tickets ouverts maximum, priorité NORMAL
• **PREMIUM** : 5 tickets ouverts maximum, priorité HIGH
• **PREMIUM PLUS** : tickets illimités, priorité URGENT

**Précisions :**
• Seuls les tickets aux statuts OPEN ou IN_PROGRESS comptent dans la limite.
• Les tickets RESOLVED ou CLOSED n''occupent pas de place.
• La priorité est attribuée automatiquement selon votre plan — elle influence l''ordre de traitement par l''équipe.

**Astuce :** si vous avez atteint votre limite en plan FREE, fermez un ticket résolu pour en ouvrir un nouveau, ou passez au plan PREMIUM pour 5 tickets simultanés.',
    'TECHNICAL', 'ticket,support,limite,plan,priorité,free,premium', 'fr', 'FREE', null, 0, true, NOW(), NOW());

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'How many support tickets can I open?',
    'The number of simultaneously open support tickets depends on your plan:

• **FREE**: 2 open tickets maximum, NORMAL priority
• **PREMIUM**: 5 open tickets maximum, HIGH priority
• **PREMIUM PLUS**: unlimited tickets, URGENT priority

**Details:**
• Only tickets with OPEN or IN_PROGRESS status count toward the limit.
• RESOLVED or CLOSED tickets do not take up a slot.
• Priority is assigned automatically based on your plan — it influences the team''s processing order.

**Tip:** if you have reached your FREE plan limit, close a resolved ticket to open a new one, or upgrade to PREMIUM for 5 simultaneous tickets.',
    'TECHNICAL', 'ticket,support,limit,plan,priority,free,premium', 'en', 'FREE', null, 0, true, NOW(), NOW());

-- ---

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'Quel est le délai de réponse du support ?',
    'Le délai de réponse dépend de la priorité de votre ticket, qui est déterminée par votre plan :

• **FREE** (priorité NORMAL) : réponse sous 72 heures ouvrées
• **PREMIUM** (priorité HIGH) : réponse sous 48 heures ouvrées
• **PREMIUM PLUS** (priorité URGENT) : réponse sous 24 heures ouvrées

**Facteurs influençant le délai :**
• Volume de tickets en cours
• Complexité de votre demande
• Jours ouvrés (lundi-vendredi)

**Pour accélérer le traitement :**
• Décrivez votre problème le plus précisément possible
• Incluez les étapes pour reproduire un bug
• Mentionnez votre navigateur et appareil si le problème est technique

Vous recevez un e-mail à chaque réponse de l''équipe.',
    'TECHNICAL', 'délai,réponse,support,temps,attente,sla', 'fr', 'FREE', null, 0, true, NOW(), NOW());

INSERT INTO joseph_support.knowledge_articles
    (id, title, content, category, tags, language, required_plan, preview_content, views, active, created_at, updated_at)
VALUES (gen_random_uuid(),
    'What is the support response time?',
    'Response time depends on your ticket priority, which is determined by your plan:

• **FREE** (NORMAL priority): response within 72 business hours
• **PREMIUM** (HIGH priority): response within 48 business hours
• **PREMIUM PLUS** (URGENT priority): response within 24 business hours

**Factors influencing response time:**
• Current ticket volume
• Complexity of your request
• Business days (Monday-Friday)

**To speed up processing:**
• Describe your issue as precisely as possible
• Include steps to reproduce a bug
• Mention your browser and device if the issue is technical

You receive an email for each team response.',
    'TECHNICAL', 'response time,support,delay,wait,sla', 'en', 'FREE', null, 0, true, NOW(), NOW());
